// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzznxvsvrsgowmuaivjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6em54dnN2cnNnb3dtdWFpdmp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3OTg5MTYsImV4cCI6MjA3MjM3NDkxNn0.AtagmJGl3iTvPMjek2sNeEBcBjOqcoXY6hYnxBizy5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});